#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ../functions
#------------------------------------------------------------------------------

cleanCase0

rm -rf constant/coarseMesh system/coarseMesh

# -----------------------------------------------------------------------------
